export const CORNELL_RESIDENCE_HALLS = [
  // North Campus (First-Year)
  { value: "Balch Hall", label: "Balch Hall", group: "North Campus" },
  { value: "Barbara McClintock Hall", label: "Barbara McClintock Hall", group: "North Campus" },
  { value: "Clara Dickson Hall", label: "Clara Dickson Hall", group: "North Campus" },
  { value: "Court-Kay-Bauer Hall", label: "Court-Kay-Bauer Hall", group: "North Campus" },
  { value: "High Rise #5", label: "High Rise #5", group: "North Campus" },
  { value: "Hu Shih Hall", label: "Hu Shih Hall", group: "North Campus" },
  { value: "Jameson Hall", label: "Jameson Hall", group: "North Campus" },
  { value: "Low Rise #6", label: "Low Rise #6", group: "North Campus" },
  { value: "Low Rise #7", label: "Low Rise #7", group: "North Campus" },
  { value: "Mary Donlon Hall", label: "Mary Donlon Hall", group: "North Campus" },
  { value: "Mews Hall", label: "Mews Hall", group: "North Campus" },
  { value: "Ruth Bader Ginsburg Hall", label: "Ruth Bader Ginsburg Hall", group: "North Campus" },
  // North Campus (Program Houses)
  { value: "Akwe:kon", label: "Akwe:kon", group: "Program Houses" },
  { value: "Holland International Living Center", label: "Holland International Living Center", group: "Program Houses" },
  { value: "Just About Music (JAM)", label: "Just About Music (JAM)", group: "Program Houses" },
  { value: "Latino Living Center", label: "Latino Living Center", group: "Program Houses" },
  { value: "Language House", label: "Language House", group: "Program Houses" },
  { value: "Loving House", label: "Loving House", group: "Program Houses" },
  { value: "Multicultural Living Learning Unit", label: "Multicultural Living Learning Unit", group: "Program Houses" },
  { value: "Risley Residential College", label: "Risley Residential College", group: "Program Houses" },
  { value: "Ujamaa Residential College", label: "Ujamaa Residential College", group: "Program Houses" },
  // North Campus (Upper-Level)
  { value: "Ganedago Hall", label: "Ganedago Hall", group: "North Campus Upper-Level" },
  { value: "Toni Morrison Hall", label: "Toni Morrison Hall", group: "North Campus Upper-Level" },
  { value: "Townhouse Apartments", label: "Townhouse Apartments", group: "North Campus Upper-Level" },
  // West Campus
  { value: "Alice Cook House", label: "Alice Cook House", group: "West Campus" },
  { value: "Carl Becker House", label: "Carl Becker House", group: "West Campus" },
  { value: "Flora Rose House", label: "Flora Rose House", group: "West Campus" },
  { value: "Hans Bethe House", label: "Hans Bethe House", group: "West Campus" },
  { value: "William Keeton House", label: "William Keeton House", group: "West Campus" },
  // South Campus
  { value: "Cascadilla Hall", label: "Cascadilla Hall", group: "South Campus" },
  { value: "Schuyler House", label: "Schuyler House", group: "South Campus" },
  { value: "Sheldon Court", label: "Sheldon Court", group: "South Campus" },
  // Cooperative Housing
  { value: "Prospect of Whitby", label: "Prospect of Whitby", group: "Cooperative Housing" },
  { value: "Triphammer Cooperative", label: "Triphammer Cooperative", group: "Cooperative Housing" },
  { value: "Von Cramm Hall", label: "Von Cramm Hall", group: "Cooperative Housing" },
  { value: "Wait Avenue Cooperative", label: "Wait Avenue Cooperative", group: "Cooperative Housing" },
  { value: "Wait Terrace", label: "Wait Terrace", group: "Cooperative Housing" },
  { value: "Wari Cooperative", label: "Wari Cooperative", group: "Cooperative Housing" },
  { value: "Watermargin", label: "Watermargin", group: "Cooperative Housing" },
  // Off-Campus
  { value: "Off-Campus", label: "Off-Campus", group: "Other" },
  { value: "Collegetown", label: "Collegetown", group: "Other" },
]
